language: go

go:
  - 1.2
  - 1.3
  - tip

install:
# hg >~ 2.5 is needed, but Travis CI's Ubuntu 12.04 ships with hg ~2.0
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update
  - sudo apt-get install mercurial

  - ./build
