language: go

go:
  - 1.2
  - 1.3
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/go-vcs
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/go-vcs

install:
# hg >~ 2.5 is needed, but Travis CI's Ubuntu 12.04 ships with hg ~2.0
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update
  - sudo apt-get install mercurial
  - sudo apt-get install libssh2-1-dev

  - ./build
