language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/go-vcs
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/go-vcs
  # hg >~ 2.5 is needed, but Travis CI's Ubuntu 12.04 ships with hg ~2.0
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update -q
  - sudo apt-get install -qq mercurial cmake libssh2-1-dev libssl-dev
  - sudo easy_install python-hglib

install:
  - cd $TRAVIS_BUILD_DIR
  - go get -t -v -d ./...
  - cd $HOME/gopath/src/github.com/libgit2/git2go && git submodule update --init && cd $TRAVIS_BUILD_DIR
  - make install

script:
  - make test
